version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: git clone https://github.com/ulrlaro/Labo_2_backend
      - run: cd Labo_2_backend && npm install
      - run: cd Labo_2_backend && npm run test 
  integrationFrontend:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: git clone https://github.com/ulrlaro/Labo_2_backend
      - run: git clone https://github.com/ulrlaro/Labo_2_frontend
      - run: cd Labo_2_frontend && npm install
      - run: cd Labo_2_frontend && npm run build 
      - run: cd Labo_2_backend && mkdir public
      - run: cd Labo_2_backend && ls -al
      - run: cp -rT Labo_2_frontend/build Labo_2_backend/public
      - run: cd Labo_2_backend/public && ls -al
      - persist_to_workspace:
          root: .
          paths:
            - Labo_2_backend
  deploiement:
    docker:
      - image: cimg/node:17.2.0
    
    steps:
      - attach_workspace:
          at: .
      - run: cd Labo_2_backend && ls -al

workflows:
  workflow:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
